=begin
#ALICE Bookkeeping

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'date'

module OpenapiClient
  class LogSubtype
    RUN = "run".freeze
    SUBSYSTEM = "subsystem".freeze
    ANNOUNCEMENT = "announcement".freeze
    INTERVENTION = "intervention".freeze
    COMMENT = "comment".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = LogSubtype.constants.select { |c| LogSubtype::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #LogSubtype" if constantValues.empty?
      value
    end
  end
end
