/**
 * ALICE Bookkeeping
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.3.1.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * DeployInformation.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_DeployInformation_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_DeployInformation_H_


#include "../ModelBase.h"


namespace org {
namespace openapitools {
namespace client {
namespace model {


/// <summary>
/// 
/// </summary>
class  DeployInformation
    : public ModelBase
{
public:
    DeployInformation();
    virtual ~DeployInformation();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// DeployInformation members

    /// <summary>
    /// 
    /// </summary>
    double getAge() const;
    bool ageIsSet() const;
    void unsetAge();

    void setAge(double value);

    /// <summary>
    /// 
    /// </summary>
    double getStart() const;
    bool startIsSet() const;
    void unsetStart();

    void setStart(double value);


protected:
    double m_Age;
    bool m_AgeIsSet;
    double m_Start;
    bool m_StartIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_DeployInformation_H_ */
