/**
 * ALICE Bookkeeping
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.3.1.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Subsystem.h
 *
 * A label attached to something for the purpose of identification.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Subsystem_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Subsystem_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {


/// <summary>
/// A label attached to something for the purpose of identification.
/// </summary>
class  Subsystem
    : public ModelBase
{
public:
    Subsystem();
    virtual ~Subsystem();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Subsystem members

    /// <summary>
    /// The unique identifier of this entity.
    /// </summary>
    int64_t getId() const;
    bool idIsSet() const;
    void unsetId();

    void setId(int64_t value);

    /// <summary>
    /// The label value of the subsystem.
    /// </summary>
    utility::string_t getText() const;
    bool textIsSet() const;
    void unsetText();

    void setText(const utility::string_t& value);

    /// <summary>
    /// Date when the subsystem was created.
    /// </summary>
    utility::string_t getCreatedAt() const;
    bool createdAtIsSet() const;
    void unsetCreatedAt();

    void setCreatedAt(const utility::string_t& value);

    /// <summary>
    /// Date when the subsystem was last updated.
    /// </summary>
    utility::string_t getUpdateAt() const;
    bool updateAtIsSet() const;
    void unsetUpdateAt();

    void setUpdateAt(const utility::string_t& value);


protected:
    int64_t m_Id;
    bool m_IdIsSet;
    utility::string_t m_Text;
    bool m_TextIsSet;
    utility::string_t m_CreatedAt;
    bool m_CreatedAtIsSet;
    utility::string_t m_UpdateAt;
    bool m_UpdateAtIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Subsystem_H_ */
