=begin
#ALICE Bookkeeping

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::CreateSubsystem
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CreateSubsystem' do
  before do
    # run before each test
    @instance = OpenapiClient::CreateSubsystem.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CreateSubsystem' do
    it 'should create an instance of CreateSubsystem' do
      expect(@instance).to be_instance_of(OpenapiClient::CreateSubsystem)
    end
  end
  describe 'test attribute "text"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
