=begin
#ALICE Bookkeeping

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::LogSubtype
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'LogSubtype' do
  before do
    # run before each test
    @instance = OpenapiClient::LogSubtype.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LogSubtype' do
    it 'should create an instance of LogSubtype' do
      expect(@instance).to be_instance_of(OpenapiClient::LogSubtype)
    end
  end
end
