/*
 * ALICE Bookkeeping
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ArrayOfSubsystemsResponse;
import org.openapitools.client.model.CreateSubsystem;
import org.openapitools.client.model.Errors;
import org.openapitools.client.model.PaginationOptions;
import org.openapitools.client.model.SubsystemResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SubsystemApi
 */
@Ignore
public class SubsystemApiTest {

    private final SubsystemApi api = new SubsystemApi();

    
    /**
     * Adds a new subsystem
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createSubsystemTest() throws ApiException {
        CreateSubsystem createSubsystem = null;
        SubsystemResponse response = api.createSubsystem(createSubsystem);

        // TODO: test validations
    }
    
    /**
     * Deletes a subsystem by Id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteSubsystemTest() throws ApiException {
        Long subsystemId = null;
        SubsystemResponse response = api.deleteSubsystem(subsystemId);

        // TODO: test validations
    }
    
    /**
     * Get a subsystem by Id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSubsystemTest() throws ApiException {
        Long subsystemId = null;
        SubsystemResponse response = api.getSubsystem(subsystemId);

        // TODO: test validations
    }
    
    /**
     * List all subsystems
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listSubsystemsTest() throws ApiException {
        PaginationOptions page = null;
        ArrayOfSubsystemsResponse response = api.listSubsystems(page);

        // TODO: test validations
    }
    
}
