/*
 * ALICE Bookkeeping
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ArrayOfTagsResponse;
import org.openapitools.client.model.Errors;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TagApi
 */
@Ignore
public class TagApiTest {

    private final TagApi api = new TagApi();

    
    /**
     * List all tags
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listTagsTest() throws ApiException {
        Integer pageOffset = null;
        Integer pageLimit = null;
        ArrayOfTagsResponse response = api.listTags(pageOffset, pageLimit);

        // TODO: test validations
    }
    
    /**
     * Lists all tags associated with a log
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listTagsByLogIdTest() throws ApiException {
        Long logId = null;
        ArrayOfTagsResponse response = api.listTagsByLogId(logId);

        // TODO: test validations
    }
    
}
