/**
 * ALICE Bookkeeping
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PaginationMeta from './PaginationMeta';

/**
 * The ArrayOfLogsResponseMeta model module.
 * @module model/ArrayOfLogsResponseMeta
 * @version 0.0.0
 */
class ArrayOfLogsResponseMeta {
    /**
     * Constructs a new <code>ArrayOfLogsResponseMeta</code>.
     * The metadata related to an array of logs response.
     * @alias module:model/ArrayOfLogsResponseMeta
     * @param page {module:model/PaginationMeta} 
     */
    constructor(page) { 
        
        ArrayOfLogsResponseMeta.initialize(this, page);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, page) { 
        obj['page'] = page;
    }

    /**
     * Constructs a <code>ArrayOfLogsResponseMeta</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ArrayOfLogsResponseMeta} obj Optional instance to populate.
     * @return {module:model/ArrayOfLogsResponseMeta} The populated <code>ArrayOfLogsResponseMeta</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ArrayOfLogsResponseMeta();

            if (data.hasOwnProperty('page')) {
                obj['page'] = PaginationMeta.constructFromObject(data['page']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/PaginationMeta} page
 */
ArrayOfLogsResponseMeta.prototype['page'] = undefined;






export default ArrayOfLogsResponseMeta;

