/**
 * ALICE Bookkeeping
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OneOfarrayobject from './OneOfarrayobject';

/**
 * The DataResponse model module.
 * @module model/DataResponse
 * @version 0.0.0
 */
class DataResponse {
    /**
     * Constructs a new <code>DataResponse</code>.
     * @alias module:model/DataResponse
     * @param data {module:model/OneOfarrayobject} 
     */
    constructor(data) { 
        
        DataResponse.initialize(this, data);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, data) { 
        obj['data'] = data;
    }

    /**
     * Constructs a <code>DataResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DataResponse} obj Optional instance to populate.
     * @return {module:model/DataResponse} The populated <code>DataResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DataResponse();

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], OneOfarrayobject);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/OneOfarrayobject} data
 */
DataResponse.prototype['data'] = undefined;






export default DataResponse;

