/**
 * ALICE Bookkeeping
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Log model module.
 * @module model/Log
 * @version 0.0.0
 */
class Log {
    /**
     * Constructs a new <code>Log</code>.
     * Describes an intervention or an event that happened.
     * @alias module:model/Log
     * @param entryId {Number} Id of the log.
     * @param title {String} Title of the log.
     * @param origin {module:model/Log.OriginEnum} Type of creator.
     * @param tags {Array.<String>} A list of Tag objects.
     */
    constructor(entryId, title, origin, tags) { 
        
        Log.initialize(this, entryId, title, origin, tags);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, entryId, title, origin, tags) { 
        obj['entryId'] = entryId;
        obj['title'] = title;
        obj['origin'] = origin;
        obj['tags'] = tags;
    }

    /**
     * Constructs a <code>Log</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Log} obj Optional instance to populate.
     * @return {module:model/Log} The populated <code>Log</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Log();

            if (data.hasOwnProperty('entryId')) {
                obj['entryId'] = ApiClient.convertToType(data['entryId'], 'Number');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('origin')) {
                obj['origin'] = ApiClient.convertToType(data['origin'], 'String');
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * Id of the log.
 * @member {Number} entryId
 */
Log.prototype['entryId'] = undefined;

/**
 * Title of the log.
 * @member {String} title
 */
Log.prototype['title'] = undefined;

/**
 * Type of creator.
 * @member {module:model/Log.OriginEnum} origin
 */
Log.prototype['origin'] = undefined;

/**
 * A list of Tag objects.
 * @member {Array.<String>} tags
 */
Log.prototype['tags'] = undefined;





/**
 * Allowed values for the <code>origin</code> property.
 * @enum {String}
 * @readonly
 */
Log['OriginEnum'] = {

    /**
     * value: "human"
     * @const
     */
    "human": "human",

    /**
     * value: "process"
     * @const
     */
    "process": "process"
};



export default Log;

