/**
 * ALICE Bookkeeping
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PaginationOptions model module.
 * @module model/PaginationOptions
 * @version 0.0.0
 */
class PaginationOptions {
    /**
     * Constructs a new <code>PaginationOptions</code>.
     * Specifies the pagination requirements of a request.
     * @alias module:model/PaginationOptions
     */
    constructor() { 
        
        PaginationOptions.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PaginationOptions</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaginationOptions} obj Optional instance to populate.
     * @return {module:model/PaginationOptions} The populated <code>PaginationOptions</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaginationOptions();

            if (data.hasOwnProperty('limit')) {
                obj['limit'] = ApiClient.convertToType(data['limit'], 'Number');
            }
            if (data.hasOwnProperty('offset')) {
                obj['offset'] = ApiClient.convertToType(data['offset'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * The numbers of items to return.
 * @member {Number} limit
 * @default 100
 */
PaginationOptions.prototype['limit'] = 100;

/**
 * The number of items to skip before starting to collect the result set.
 * @member {Number} offset
 * @default 0
 */
PaginationOptions.prototype['offset'] = 0;






export default PaginationOptions;

