/**
 * ALICE Bookkeeping
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Tag model module.
 * @module model/Tag
 * @version 0.0.0
 */
class Tag {
    /**
     * Constructs a new <code>Tag</code>.
     * A label attached to something for the purpose of identification.
     * @alias module:model/Tag
     * @param id {Number} Id of the tag.
     * @param text {String} The label value of the tag.
     */
    constructor(id, text) { 
        
        Tag.initialize(this, id, text);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, text) { 
        obj['id'] = id;
        obj['text'] = text;
    }

    /**
     * Constructs a <code>Tag</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Tag} obj Optional instance to populate.
     * @return {module:model/Tag} The populated <code>Tag</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Tag();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'String');
            }
            if (data.hasOwnProperty('updateAt')) {
                obj['updateAt'] = ApiClient.convertToType(data['updateAt'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Id of the tag.
 * @member {Number} id
 */
Tag.prototype['id'] = undefined;

/**
 * The label value of the tag.
 * @member {String} text
 */
Tag.prototype['text'] = undefined;

/**
 * Date when the tag was created.
 * @member {String} createdAt
 */
Tag.prototype['createdAt'] = undefined;

/**
 * Date when the tag was last updated.
 * @member {String} updateAt
 */
Tag.prototype['updateAt'] = undefined;






export default Tag;

