/*
 * ALICE Bookkeeping
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// DeployInformation : Deploy information



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeployInformation {
    /// The number of seconds that the server is online.
    #[serde(rename = "age")]
    pub age: f32,
    /// The unix timestamp of the moment that the the server went online.
    #[serde(rename = "start")]
    pub start: f32,
}

impl DeployInformation {
    /// Deploy information
    pub fn new(age: f32, start: f32) -> DeployInformation {
        DeployInformation {
            age,
            start,
        }
    }
}


