/*
 * ALICE Bookkeeping
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Log : Describes an intervention or an event that happened.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Log {
    /// The unique identifier of this entity.
    #[serde(rename = "id")]
    pub id: i64,
    /// Title of the log.
    #[serde(rename = "title")]
    pub title: String,
    /// Body of the log.
    #[serde(rename = "text")]
    pub text: String,
    #[serde(rename = "origin")]
    pub origin: crate::models::LogOrigin,
    /// A list of Tag objects.
    #[serde(rename = "tags")]
    pub tags: Vec<crate::models::Tag>,
    /// The unique identifier of this entity.
    #[serde(rename = "rootLogId")]
    pub root_log_id: i64,
    /// The unique identifier of this entity.
    #[serde(rename = "parentLogId")]
    pub parent_log_id: i64,
}

impl Log {
    /// Describes an intervention or an event that happened.
    pub fn new(id: i64, title: String, text: String, origin: crate::models::LogOrigin, tags: Vec<crate::models::Tag>, root_log_id: i64, parent_log_id: i64) -> Log {
        Log {
            id,
            title,
            text,
            origin,
            tags,
            root_log_id,
            parent_log_id,
        }
    }
}


