/*
 * ALICE Bookkeeping
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PaginationMeta : The metadata related to pagination.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaginationMeta {
    /// The total number of pages which contain data.
    #[serde(rename = "pageCount")]
    pub page_count: i32,
    /// The total number of elements in the collection
    #[serde(rename = "totalCount")]
    pub total_count: i32,
}

impl PaginationMeta {
    /// The metadata related to pagination.
    pub fn new(page_count: i32, total_count: i32) -> PaginationMeta {
        PaginationMeta {
            page_count,
            total_count,
        }
    }
}


