/*
 * ALICE Bookkeeping
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TagResponse : Response containing a single tag.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TagResponse {
    #[serde(rename = "data")]
    pub data: crate::models::Tag,
}

impl TagResponse {
    /// Response containing a single tag.
    pub fn new(data: crate::models::Tag) -> TagResponse {
        TagResponse {
            data,
        }
    }
}


