/*
 * ALICE Bookkeeping
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// CreateLog Describes an intervention or an event that happened.
type CreateLog struct {
	// Title of the log.
	Title string `json:"title"`
	// Body of the log.
	Text string `json:"text"`
	// The unique identifier of this entity.
	ParentLogId int64 `json:"parentLogId,omitempty"`
}
