/*
 * ALICE Bookkeeping
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ArrayOfTagsResponse Response containing multiple tags.
type ArrayOfTagsResponse struct {
	// A list of Tag objects.
	Data []string `json:"data"`
}
