/*
 * ALICE Bookkeeping
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Errors A list of Error objects.
type Errors struct {
	// A list of Error objects.
	Errors []Error `json:"errors"`
}
