/*
 * ALICE Bookkeeping
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Subsystem A label attached to something for the purpose of identification.
type Subsystem struct {
	// The unique identifier of this entity.
	Id int64 `json:"id"`
	// The label value of the subsystem.
	Name string `json:"name"`
	// Date when the subsystem was created.
	CreatedAt string `json:"createdAt,omitempty"`
	// Date when the subsystem was last updated.
	UpdateAt string `json:"updateAt,omitempty"`
}
