/*
 * ALICE Bookkeeping
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// SortLogsOptions Specifies the sorting requirements of a request.
type SortLogsOptions struct {
	Id SortOrder `json:"id,omitempty"`
	Text SortOrder `json:"text,omitempty"`
}
