/*
 * ALICE Bookkeeping
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// DeployInformation Deploy information
type DeployInformation struct {
	// The number of seconds that the server is online.
	Age float32 `json:"age"`
	// The unix timestamp of the moment that the the server went online.
	Start float32 `json:"start"`
}
