/*
 * ALICE Bookkeeping
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// FilterLogsOptions Specifies the log related filter requirements for a request.
type FilterLogsOptions struct {
	Origin LogOrigin `json:"origin,omitempty"`
}
