/*
 * ALICE Bookkeeping
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Tag A label attached to something for the purpose of identification.
type Tag struct {
	// Id of the tag.
	Id int64 `json:"id"`
	// The label value of the tag.
	Text string `json:"text"`
	// Date when the tag was created.
	CreatedAt string `json:"createdAt,omitempty"`
	// Date when the tag was last updated.
	UpdateAt string `json:"updateAt,omitempty"`
}
