/* 
 * ALICE Bookkeeping
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// The subtype of a Log.
    /// </summary>
    /// <value>The subtype of a Log.</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum LogSubtype
    {
        /// <summary>
        /// Enum Run for value: run
        /// </summary>
        [EnumMember(Value = "run")]
        Run = 1,

        /// <summary>
        /// Enum Subsystem for value: subsystem
        /// </summary>
        [EnumMember(Value = "subsystem")]
        Subsystem = 2,

        /// <summary>
        /// Enum Announcement for value: announcement
        /// </summary>
        [EnumMember(Value = "announcement")]
        Announcement = 3,

        /// <summary>
        /// Enum Intervention for value: intervention
        /// </summary>
        [EnumMember(Value = "intervention")]
        Intervention = 4,

        /// <summary>
        /// Enum Comment for value: comment
        /// </summary>
        [EnumMember(Value = "comment")]
        Comment = 5

    }

}
