/* 
 * ALICE Bookkeeping
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing ArrayOfSubsystemsResponseMeta
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ArrayOfSubsystemsResponseMetaTests
    {
        // TODO uncomment below to declare an instance variable for ArrayOfSubsystemsResponseMeta
        //private ArrayOfSubsystemsResponseMeta instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ArrayOfSubsystemsResponseMeta
            //instance = new ArrayOfSubsystemsResponseMeta();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ArrayOfSubsystemsResponseMeta
        /// </summary>
        [Test]
        public void ArrayOfSubsystemsResponseMetaInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ArrayOfSubsystemsResponseMeta
            //Assert.IsInstanceOf(typeof(ArrayOfSubsystemsResponseMeta), instance);
        }


        /// <summary>
        /// Test the property 'Page'
        /// </summary>
        [Test]
        public void PageTest()
        {
            // TODO unit test for the property 'Page'
        }

    }

}
