/**
 * ALICE Bookkeeping
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAICreateLog.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAICreateLog::OAICreateLog(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAICreateLog::OAICreateLog() {
    this->initializeModel();
}

OAICreateLog::~OAICreateLog() {}

void OAICreateLog::initializeModel() {

    m_title_isSet = false;
    m_title_isValid = false;

    m_text_isSet = false;
    m_text_isValid = false;
}

void OAICreateLog::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAICreateLog::fromJsonObject(QJsonObject json) {

    m_title_isValid = ::OpenAPI::fromJsonValue(title, json[QString("title")]);
    m_title_isSet = !json[QString("title")].isNull() && m_title_isValid;

    m_text_isValid = ::OpenAPI::fromJsonValue(text, json[QString("text")]);
    m_text_isSet = !json[QString("text")].isNull() && m_text_isValid;
}

QString OAICreateLog::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAICreateLog::asJsonObject() const {
    QJsonObject obj;
    if (m_title_isSet) {
        obj.insert(QString("title"), ::OpenAPI::toJsonValue(title));
    }
    if (m_text_isSet) {
        obj.insert(QString("text"), ::OpenAPI::toJsonValue(text));
    }
    return obj;
}

QString OAICreateLog::getTitle() const {
    return title;
}
void OAICreateLog::setTitle(const QString &title) {
    this->title = title;
    this->m_title_isSet = true;
}

bool OAICreateLog::is_title_Set() const{
    return m_title_isSet;
}

bool OAICreateLog::is_title_Valid() const{
    return m_title_isValid;
}

QString OAICreateLog::getText() const {
    return text;
}
void OAICreateLog::setText(const QString &text) {
    this->text = text;
    this->m_text_isSet = true;
}

bool OAICreateLog::is_text_Set() const{
    return m_text_isSet;
}

bool OAICreateLog::is_text_Valid() const{
    return m_text_isValid;
}

bool OAICreateLog::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_title_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_text_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAICreateLog::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_title_isValid && m_text_isValid && true;
}

} // namespace OpenAPI
