/**
 * ALICE Bookkeeping
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIDeployInformation.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIDeployInformation::OAIDeployInformation(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIDeployInformation::OAIDeployInformation() {
    this->initializeModel();
}

OAIDeployInformation::~OAIDeployInformation() {}

void OAIDeployInformation::initializeModel() {

    m_age_isSet = false;
    m_age_isValid = false;

    m_start_isSet = false;
    m_start_isValid = false;
}

void OAIDeployInformation::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIDeployInformation::fromJsonObject(QJsonObject json) {

    m_age_isValid = ::OpenAPI::fromJsonValue(age, json[QString("age")]);
    m_age_isSet = !json[QString("age")].isNull() && m_age_isValid;

    m_start_isValid = ::OpenAPI::fromJsonValue(start, json[QString("start")]);
    m_start_isSet = !json[QString("start")].isNull() && m_start_isValid;
}

QString OAIDeployInformation::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIDeployInformation::asJsonObject() const {
    QJsonObject obj;
    if (m_age_isSet) {
        obj.insert(QString("age"), ::OpenAPI::toJsonValue(age));
    }
    if (m_start_isSet) {
        obj.insert(QString("start"), ::OpenAPI::toJsonValue(start));
    }
    return obj;
}

double OAIDeployInformation::getAge() const {
    return age;
}
void OAIDeployInformation::setAge(const double &age) {
    this->age = age;
    this->m_age_isSet = true;
}

bool OAIDeployInformation::is_age_Set() const{
    return m_age_isSet;
}

bool OAIDeployInformation::is_age_Valid() const{
    return m_age_isValid;
}

double OAIDeployInformation::getStart() const {
    return start;
}
void OAIDeployInformation::setStart(const double &start) {
    this->start = start;
    this->m_start_isSet = true;
}

bool OAIDeployInformation::is_start_Set() const{
    return m_start_isSet;
}

bool OAIDeployInformation::is_start_Valid() const{
    return m_start_isValid;
}

bool OAIDeployInformation::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_age_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_start_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIDeployInformation::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_age_isValid && m_start_isValid && true;
}

} // namespace OpenAPI
