/**
 * ALICE Bookkeeping
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIDeployInformation.h
 *
 * Deploy information
 */

#ifndef OAIDeployInformation_H
#define OAIDeployInformation_H

#include <QJsonObject>


#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIDeployInformation : public OAIObject {
public:
    OAIDeployInformation();
    OAIDeployInformation(QString json);
    ~OAIDeployInformation() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    double getAge() const;
    void setAge(const double &age);
    bool is_age_Set() const;
    bool is_age_Valid() const;

    double getStart() const;
    void setStart(const double &start);
    bool is_start_Set() const;
    bool is_start_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    double age;
    bool m_age_isSet;
    bool m_age_isValid;

    double start;
    bool m_start_isSet;
    bool m_start_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIDeployInformation)

#endif // OAIDeployInformation_H
