/**
 * ALICE Bookkeeping
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIFilterLogsOptions.h
 *
 * Specifies the log related filter requirements for a request.
 */

#ifndef OAIFilterLogsOptions_H
#define OAIFilterLogsOptions_H

#include <QJsonObject>

#include "OAIFilterLogsTagOptions.h"
#include "OAILogOrigin.h"

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIFilterLogsOptions : public OAIObject {
public:
    OAIFilterLogsOptions();
    OAIFilterLogsOptions(QString json);
    ~OAIFilterLogsOptions() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    OAILogOrigin getOrigin() const;
    void setOrigin(const OAILogOrigin &origin);
    bool is_origin_Set() const;
    bool is_origin_Valid() const;

    qint64 getParentLog() const;
    void setParentLog(const qint64 &parent_log);
    bool is_parent_log_Set() const;
    bool is_parent_log_Valid() const;

    qint64 getRootLog() const;
    void setRootLog(const qint64 &root_log);
    bool is_root_log_Set() const;
    bool is_root_log_Valid() const;

    OAIFilterLogsTagOptions getTag() const;
    void setTag(const OAIFilterLogsTagOptions &tag);
    bool is_tag_Set() const;
    bool is_tag_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    OAILogOrigin origin;
    bool m_origin_isSet;
    bool m_origin_isValid;

    qint64 parent_log;
    bool m_parent_log_isSet;
    bool m_parent_log_isValid;

    qint64 root_log;
    bool m_root_log_isSet;
    bool m_root_log_isValid;

    OAIFilterLogsTagOptions tag;
    bool m_tag_isSet;
    bool m_tag_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIFilterLogsOptions)

#endif // OAIFilterLogsOptions_H
