/**
 * ALICE Bookkeeping
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAILogSubtype.h
 *
 * The subtype of a Log.
 */

#ifndef OAILogSubtype_H
#define OAILogSubtype_H

#include <QJsonObject>


#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAILogSubtype : public OAIEnum {
public:
    OAILogSubtype();
    OAILogSubtype(QString json);
    ~OAILogSubtype() override;

    QString asJson() const override;
    QJsonValue asJsonValue() const override;
    void fromJsonValue(QJsonValue json) override;
    void fromJson(QString jsonString) override;

    enum class eOAILogSubtype {
        INVALID_VALUE_OPENAPI_GENERATED = 0,
        RUN, 
        SUBSYSTEM, 
        ANNOUNCEMENT, 
        INTERVENTION, 
        COMMENT
    };
    OAILogSubtype::eOAILogSubtype getValue() const;
    void setValue(const OAILogSubtype::eOAILogSubtype& value);
    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    eOAILogSubtype m_value;
    bool m_value_isSet;
    bool m_value_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAILogSubtype)

#endif // OAILogSubtype_H
