/**
 * ALICE Bookkeeping
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAILogTree.h
 *
 * Describes an intervention or an event that happened.
 */

#ifndef OAILogTree_H
#define OAILogTree_H

#include <QJsonObject>

#include "OAILogOrigin.h"
#include "OAILogSubtype.h"
#include "OAITag.h"
#include <QList>
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAILogTree : public OAIObject {
public:
    OAILogTree();
    OAILogTree(QString json);
    ~OAILogTree() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    qint64 getId() const;
    void setId(const qint64 &id);
    bool is_id_Set() const;
    bool is_id_Valid() const;

    QString getAuthorId() const;
    void setAuthorId(const QString &author_id);
    bool is_author_id_Set() const;
    bool is_author_id_Valid() const;

    QString getTitle() const;
    void setTitle(const QString &title);
    bool is_title_Set() const;
    bool is_title_Valid() const;

    QString getText() const;
    void setText(const QString &text);
    bool is_text_Set() const;
    bool is_text_Valid() const;

    qint64 getCreationTime() const;
    void setCreationTime(const qint64 &creation_time);
    bool is_creation_time_Set() const;
    bool is_creation_time_Valid() const;

    OAILogOrigin getOrigin() const;
    void setOrigin(const OAILogOrigin &origin);
    bool is_origin_Set() const;
    bool is_origin_Valid() const;

    OAILogSubtype getSubtype() const;
    void setSubtype(const OAILogSubtype &subtype);
    bool is_subtype_Set() const;
    bool is_subtype_Valid() const;

    QList<OAITag> getTags() const;
    void setTags(const QList<OAITag> &tags);
    bool is_tags_Set() const;
    bool is_tags_Valid() const;

    qint64 getRootLogId() const;
    void setRootLogId(const qint64 &root_log_id);
    bool is_root_log_id_Set() const;
    bool is_root_log_id_Valid() const;

    qint64 getParentLogId() const;
    void setParentLogId(const qint64 &parent_log_id);
    bool is_parent_log_id_Set() const;
    bool is_parent_log_id_Valid() const;

    QList<OAILogTree> getChildren() const;
    void setChildren(const QList<OAILogTree> &children);
    bool is_children_Set() const;
    bool is_children_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    qint64 id;
    bool m_id_isSet;
    bool m_id_isValid;

    QString author_id;
    bool m_author_id_isSet;
    bool m_author_id_isValid;

    QString title;
    bool m_title_isSet;
    bool m_title_isValid;

    QString text;
    bool m_text_isSet;
    bool m_text_isValid;

    qint64 creation_time;
    bool m_creation_time_isSet;
    bool m_creation_time_isValid;

    OAILogOrigin origin;
    bool m_origin_isSet;
    bool m_origin_isValid;

    OAILogSubtype subtype;
    bool m_subtype_isSet;
    bool m_subtype_isValid;

    QList<OAITag> tags;
    bool m_tags_isSet;
    bool m_tags_isValid;

    qint64 root_log_id;
    bool m_root_log_id_isSet;
    bool m_root_log_id_isValid;

    qint64 parent_log_id;
    bool m_parent_log_id_isSet;
    bool m_parent_log_id_isValid;

    QList<OAILogTree> children;
    bool m_children_isSet;
    bool m_children_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAILogTree)

#endif // OAILogTree_H
