/**
 * ALICE Bookkeeping
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIPaginationMeta.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIPaginationMeta::OAIPaginationMeta(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIPaginationMeta::OAIPaginationMeta() {
    this->initializeModel();
}

OAIPaginationMeta::~OAIPaginationMeta() {}

void OAIPaginationMeta::initializeModel() {

    m_total_isSet = false;
    m_total_isValid = false;
}

void OAIPaginationMeta::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIPaginationMeta::fromJsonObject(QJsonObject json) {

    m_total_isValid = ::OpenAPI::fromJsonValue(total, json[QString("total")]);
    m_total_isSet = !json[QString("total")].isNull() && m_total_isValid;
}

QString OAIPaginationMeta::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIPaginationMeta::asJsonObject() const {
    QJsonObject obj;
    if (m_total_isSet) {
        obj.insert(QString("total"), ::OpenAPI::toJsonValue(total));
    }
    return obj;
}

qint32 OAIPaginationMeta::getTotal() const {
    return total;
}
void OAIPaginationMeta::setTotal(const qint32 &total) {
    this->total = total;
    this->m_total_isSet = true;
}

bool OAIPaginationMeta::is_total_Set() const{
    return m_total_isSet;
}

bool OAIPaginationMeta::is_total_Valid() const{
    return m_total_isValid;
}

bool OAIPaginationMeta::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_total_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIPaginationMeta::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_total_isValid && true;
}

} // namespace OpenAPI
