/**
 * ALICE Bookkeeping
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAISortLogsOptions.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAISortLogsOptions::OAISortLogsOptions(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAISortLogsOptions::OAISortLogsOptions() {
    this->initializeModel();
}

OAISortLogsOptions::~OAISortLogsOptions() {}

void OAISortLogsOptions::initializeModel() {

    m_id_isSet = false;
    m_id_isValid = false;

    m_text_isSet = false;
    m_text_isValid = false;
}

void OAISortLogsOptions::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAISortLogsOptions::fromJsonObject(QJsonObject json) {

    m_id_isValid = ::OpenAPI::fromJsonValue(id, json[QString("id")]);
    m_id_isSet = !json[QString("id")].isNull() && m_id_isValid;

    m_text_isValid = ::OpenAPI::fromJsonValue(text, json[QString("text")]);
    m_text_isSet = !json[QString("text")].isNull() && m_text_isValid;
}

QString OAISortLogsOptions::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAISortLogsOptions::asJsonObject() const {
    QJsonObject obj;
    if (id.isSet()) {
        obj.insert(QString("id"), ::OpenAPI::toJsonValue(id));
    }
    if (text.isSet()) {
        obj.insert(QString("text"), ::OpenAPI::toJsonValue(text));
    }
    return obj;
}

OAISortOrder OAISortLogsOptions::getId() const {
    return id;
}
void OAISortLogsOptions::setId(const OAISortOrder &id) {
    this->id = id;
    this->m_id_isSet = true;
}

bool OAISortLogsOptions::is_id_Set() const{
    return m_id_isSet;
}

bool OAISortLogsOptions::is_id_Valid() const{
    return m_id_isValid;
}

OAISortOrder OAISortLogsOptions::getText() const {
    return text;
}
void OAISortLogsOptions::setText(const OAISortOrder &text) {
    this->text = text;
    this->m_text_isSet = true;
}

bool OAISortLogsOptions::is_text_Set() const{
    return m_text_isSet;
}

bool OAISortLogsOptions::is_text_Valid() const{
    return m_text_isValid;
}

bool OAISortLogsOptions::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (id.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (text.isSet()) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAISortLogsOptions::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
