openapi: 3.0.0
info:
  title: ALICE Bookkeeping
  version: 0.0.0
servers:
- url: /api
paths:
  /:
    get:
      operationId: getServerInformation
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiInformation'
          description: API information
        "503":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Service Unavailable
      summary: Get server information
      x-accepts: application/json
  /logs:
    get:
      operationId: listLogs
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfLogsResponse'
          description: Expected response to a valid request.
      summary: List all logs
      tags:
      - log
      x-accepts: application/json
    post:
      operationId: createLog
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LogResponse'
          description: Expected response to a valid request.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Bad Request
      summary: Adds a new log
      tags:
      - log
      x-accepts: application/json
  /logs/{id}:
    get:
      operationId: getLogById
      parameters:
      - description: The id of the log to retrieve
        explode: false
        in: path
        name: id
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LogResponse'
          description: Expected response to a valid request.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Bad Request
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Not Found
      summary: Gets a log by Id
      tags:
      - log
      x-accepts: application/json
  /status:
    get:
      operationId: getDeployInformation
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeployInformation'
          description: Deploy information
        "503":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Service Unavailable
      summary: Get deploy information
      x-accepts: application/json
components:
  responses:
    ArrayOfLogs:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ArrayOfLogsResponse'
      description: Expected response to a valid request.
    BadRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
      description: Bad Request
    Log:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/LogResponse'
      description: Expected response to a valid request.
    NotFound:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
      description: Not Found
    ServiceUnavailable:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
      description: Service Unavailable
  schemas:
    ApiInformation:
      description: API information
      example:
        name: name
        version: version
      properties:
        name:
          description: Name of the API
          type: string
        version:
          description: Version of the API
          type: string
      required:
      - name
      - version
      type: object
    ArrayOfLogs:
      description: A list of Log objects.
      items:
        $ref: '#/components/schemas/Log'
      type: array
    ArrayOfLogsResponse:
      description: Response containing multiple logs.
      example:
        data:
        - title: title
        - title: title
      properties:
        data:
          description: A list of Log objects.
          items:
            $ref: '#/components/schemas/Log'
          type: array
      required:
      - data
      type: object
    DeployInformation:
      description: Deploy information
      example:
        start: 6.027456183070403
        age: 0.8008281904610115
      properties:
        age:
          description: The number of seconds that the server is online.
          type: number
        start:
          description: The unix timestamp of the moment that the the server went online.
          type: number
      required:
      - age
      - start
      type: object
    Error:
      description: An Error object.
      properties:
        status:
          description: The HTTP status code applicable to this problem.
          type: string
        title:
          description: A short, human-readable summary of the problem.
          type: string
        detail:
          description: A human-readable explanation specific to this occurrence of
            the problem.
          type: string
      required:
      - status
      - title
      type: object
    Errors:
      description: A list of Error objects.
      properties:
        errors:
          description: A list of Error objects.
          items:
            $ref: '#/components/schemas/Error'
          minItems: 1
          type: array
      required:
      - errors
      type: object
    Log:
      description: Describes an intervention or an event that happened.
      example:
        title: title
      properties:
        title:
          description: Title of the log.
          type: string
      required:
      - title
      type: object
    LogResponse:
      description: Response containing a single log.
      example:
        data:
          title: title
      properties:
        data:
          $ref: '#/components/schemas/Log'
      required:
      - data
      type: object

